### ISSUE TITLE
Arguments from higher level should not be mutable

### ISSUE THREAD

**Issue by Eraden** [imanel/servicer#2]
https://github.com/imanel/servicer/blob/d3e451df43778b8d1ddeae0b65d639ea9333c87c/lib/servicer/base.rb#L45

Accidental mutation can cause failures in caller.

**Comment by imanel** [comment]
This is the case for both `current_user` and `params`. I could use `dup` here, but that would prevent only part of changes (on top level), and not deep down. At the same time it would make execution slower and increate memory footprint, so I decided that it's up to developer to not modify passed values, similar to most other methods in Ruby.
